export const FORMULARIO_ACTIVIDAD = 'FORMULARIO_ACTIVIDAD'
export const OBTENER_ACTIVIDADES = 'OBTENER_ACTIVIDADES'
export const AGREGAR_ACTIVIDAD = 'AGREGAR_ACTIVIDAD'
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO'
export const ELIMINAR_ACTIVIDAD = 'ELIMINAR_ACTIVIDAD'
export const ACTIVIDAD_ACTUAL = 'ACTIVIDAD ACTUAL'
export const ACTUALIZAR_ACTIVIDAD = 'ACTUALIZARACTIVIDAD'
export const OCULTAR_FORMULARIO = 'OCULATAR_FORMULARIO'

export const FORMULARIO_BENEFICIARIO = 'FORMULARIO_BENEFICIARIO'
export const OBTENER_BENEFICIARIOS = 'OBTENER_BENEFICIARIOS'
export const AGREGAR_BENEFICIARIO = 'AGREGAR_BENEFICIARIO'
export const VALIDAR_FORMULARIO_B = 'VALIDAR_FORMULARIO_B'
export const ELIMINAR_ATRIBUTOS_BENEFICIARIO = 'ELIMINAR_ATRIBUTOS_BENEFICIARIO'
export const BENEFICIARIO_ACTUAL = 'BENEFICIARIO_ACTUAL'
export const ACTUALIZAR_BENEFICIARIO = 'ACTUALIZAR_BENEFICIARIO'
export const OCULTAR_FORMULARIO_B = 'OCULTAR_FORMULARIO_B'
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'



export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'
