export const FORMULARIO_ACTIVIDAD = 'FORMULARIO_ACTIVIDAD'
export const OBTENER_ACTIVIDADES = 'OBTENER_ACTIVIDADES'
export const AGREGAR_ACTIVIDAD = 'AGREGAR_ACTIVIDAD'
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO'
export const ELIMINAR_ACTIVIDAD = 'ELIMINAR_ACTIVIDAD'
export const ACTIVIDAD_ACTUAL = 'ACTIVIDAD ACTUAL'
export const ACTUALIZAR_ACTIVIDAD = 'ACTUALIZARACTIVIDAD'
export const OCULTAR_FORMULARIO = 'OCULATAR_FORMULARIO'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'



export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'
